Repository pscedu/singularity-hyperfine, pull requests merged in 2021-06, with the labels that each got.

#2 Create test.sh
  1.11.0/test.sh
Labels: enhancement

#7 Added modulefile
  1.11.0/Singularity
  1.11.0/modulefile.lua
Labels: enhancement

#8 Delete stale.yml
  .github/workflows/stale.yml
Labels: enhancement

#9 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement

#11 Update README.md
  README.md
Labels: documentation

#10 Update modulefile.lua
  1.11.0/modulefile.lua
Labels: documentation
